# Generated by Django 3.1.7 on 2021-03-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeExt', '0003_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('directions', models.CharField(max_length=5000)),
                ('prep_time', models.DurationField()),
                ('cook_time', models.DurationField()),
                ('total_time', models.DurationField()),
                ('serving_size', models.IntegerField(default=1)),
                ('nutritional_info', models.CharField(max_length=200)),
                ('thumbnail_url', models.URLField(max_length=100)),
                ('source', models.URLField(max_length=100)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='chef',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_string', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeExt.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeExt.recipe')),
            ],
            options={
                'ordering': ('recipe', 'ingredient'),
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeExt.chef'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='RecipeExt.RecipeIngredient', to='RecipeExt.Ingredient'),
        ),
    ]
