# Generated by Django 3.1.7 on 2021-03-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeExt', '0004_auto_20210328_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutritional_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.DurationField(blank=True),
        ),
    ]
