# Generated by Django 3.1.7 on 2021-03-28 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecipeExt', '0006_auto_20210328_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'ordering': ('user',)},
        ),
        migrations.RemoveField(
            model_name='chef',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='last_name',
        ),
        migrations.AddField(
            model_name='chef',
            name='about_me',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='chef',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='chef',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
